### ISSUE TITLE
native arm support

### ISSUE THREAD

**Issue by imhlq** [XmacsLabs/mogan#367]
Would like to have native m1 arm support on release!

**Comment by pan93412** [comment]
I have attempted to build the binary for M1 in my GitHub Actions – which seems not simple. As Mogan depends on some binaries that did not ship with the `arm64` variant, it failed on the link stage. [ci](https://github.com/pan93412/mogan/actions/runs/3566850119/jobs/5993807617)

Maybe we can sign up a *free* M1 machine (for only this purpose) for building Mogan, so we don't need to stick to the complex cross-compiling way: <https://www.macstadium.com/opensource>. This is what the IINA team does for compiling M1: <https://github.com/iina-plus/iina/issues/23> [ci](https://github.com/iina-plus/iina/actions/runs/3217557988/jobs/5260668411)

Another way to achieve our mission is [building our Qt binaries that include the arm64 variant](https://github.com/qbittorrent/qBittorrent/wiki/Compilation:-macOS-(x86_64,-arm64,-cross-compilation)#qt). Nonetheless, “building our own Qt” may produce more issues (and make the compilation slow); besides, some system binaries can't be fixed in this way. “Cross compile” is complex and time-consuming – avoiding it is always the wise choice.

**Comment by darcy-shen** [comment]
Hopefully, M1 support will be available for Mogan v1.1.2. Here is the roadmap: http://forum.texmacs.cn/t/mogan-v1-1-2-roadmap/1174

**Comment by darcy-shen** [comment]
Available via `packages/macos/package.sh`

**Comment by darcy-shen** [comment]
Yes. https://gitee.com/XmacsLabs/mogan/attach_files Try alpha2 if you are interested and wanna take the risk.

**Comment by darcy-shen** [comment]
Here is the magic link without logining into Gitee: https://gitee.com/XmacsLabs/mogan/attach_files/1275978/download

**Comment by darcy-shen** [comment]
>  Is there a way to make sure I'm notified when it gets released?

No notification now. You can check manually via `Help -> Mogan` document. Currently, only English and Chinese available as:
+ https://github.com/XmacsLabs/planet/blob/main/doc/welcome.en.tm
+ https://github.com/XmacsLabs/planet/blob/main/doc/welcome.zh.tm

What's your native language? I wonder if you'd like to create a pull request to add a Mogan welcome doc in your native language.

**Comment by darcy-shen** [comment]
NOTICE: Mogan Editor is made on Earth but not made in China!

**Comment by Iey4iej3** [comment]
Is it currently possible to run Mogan on `arm64` under Linux? I imagine running a Linux distro on AnLinux on Android without `x86` emulator.
